name: 'caracare_casestudy'
version: '1.0.0'
config-version: 2

profile: 'databricks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  caracare_casestudy:
    dimensions:
      +materialized: table
      +schema: 00_bronze
    facts:
      +materialized: table
      +schema: 00_bronze